FROM python:3.12-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

COPY english_tutor ./english_tutor

CMD ["uv", "run", "--no-dev", "python", "-m", "english_tutor.main"]